
var quotes = ["Aba vakti aba, yaba vakti yaba alan yanılmaz.", 
"Abanın kadri, yağmurda bilinir.", 
"Abdal abdalın ne umduğunu, ne bulduğunu ister.", 
"Abdal ata binmiş bey oldum sanmış.", 
"Abdal düğünden, çocuk oyundan usanmaz.", 
"Abdala kar yağıyor demişler, titremeye hazırım demiş.", 
"Abdalın arkadaşlığı yol görününceye kadardır.", 
"Abdalın karnı doyunca gözü pabucundadır.", 
"Abdestsiz sofuya namaz dayanmaz.", 
"Acele giden ecele gider.", 
"Acele işe, şeytan karışır.", 
"Acele yürüyen yolda kalır.", 
"Acemi katır kapı önünde yük indirir.", 
"Acemi marangozun talaşı tahtasından çok olur.", 
"Acemi nalbant gibi kâh nalına vurur, kâh mıhına.", 
"Acı acıyı bastırır, su sancıyı.", 
"Acı patlıcanı kırağı çalmaz.", 
"Acı söz insanı dininden çıkarır, tatlı söz yılanı deliğinden çıkarır.", 
"Acıkan doymam, susayan kanmam sanır.", 
"Acıkan yanağından, susayan dudağından belli olur.", 
"Acındırırsan arsız, acıktırırsan hırsız olur.", 
"Aç ayı oynamaz.", 
"Aç aman bilmez, çocuk zaman bilmez.", 
"Aç bırakma hırsız edersin, çok söyleme arsız edersin.", 
"Aç doymam, tok acıkmam sanır.", 
"Aç koyma hırsız olur, çok söyleme yüzsüz olur, çok değme arsız olur.", 
"Aç koynunda azık durmaz.", 
"Aç köpek fırın deler.", 
"Aç kurt arslana saldırır.", 
"Aç tavuk rüyasında kendini buğday ambarında görür.", 
"Aç tokun halinden anlamaz.", 
"Aça dokuz yorgan örtmüşler, yine uyuyamamış.", 
"Açık yaraya kurt düşmez.", 
"Açık ağız aç kalmaz.", 
"Açık yerde tepecik kendini dağ sanır.", 
"Açılan solar, ağlayan güler.", 
"Açın imanı olmaz.", 
"Açın karnı doyar gözü doymaz.", 
"Açlık ile tokluğun arası bir dilim ekmek.", 
"Açtırma kutuyu, söyletme kötüyü.", 
"Adam adamdır olmasa da pulu, eşek eşektir olsa da çulu.", 
"Adam eşeğinden, kadın döşeğinden belli olur.", 
"Adam kıtlığında keçiye Abdurrahman Çelebi derler.", 
"Adam olana bir söz yeter.", 
"Adam sandık eşeği, altına serdik döşeği.", 
"Adam yenilmekle marifetli olur, yanılmakla âlim.", 
"Adamak kolay, ödemek güçtür.", 
"Adamakla mal tükenmez.", 
"Adamın iyisi iş başında belli olur.", 
"Adı çıkacağına canı çıksın.", 
"Adı çıktı dokuza, inmez sekize.", 
"Ağaç kökünden yıkılır.", 
"Ağaç ne kadar meyve verirse, dalı o kadar yere eğilir.", 
"Ağaç ne kadar uzarsa uzasın göğe değmez.", 
"Ağaç ne kadar yüksek olsa da yaprakları yere düşer.", 
"Ağaç ucuna yel değer, güzel kişiye söz değer.", 
"Ağaç yaşken eğilir.", 
"Ağaca balta vurmuşlar sapı bendendir demiş.", 
"Ağaca beşikten mezara kadar muhtacız.", 
"Ağaca çıkan keçinin dama çıkan oğlağı olur.", 
"Ağaca çıkan keçinin dala bakan oğlağı olur.", 
"Ağaca dayanma çürür, insana güvenme ölür.", 
"Ağacı kurt, insanı dert bitirir.", 
"Ağaçlı köyü su basmaz.", 
"Ağaçsız memleket duvaksız geline benzer.", 
"Ağaçtan maşa, aptaldan paşa olmaz.", 
"Ağaran baş, ağlayan göz gizlenmez.", 
"Ağır baş iyidir, yenlik olsa uçar.", 
"Ağır git ki yol alasın.", 
"Ağır kazan geç kaynar.", 
"Ağır otur, batman götür.", 
"Ağır taş batman döver.", 
"Ağır taş yerinden oynamaz.", 
"Ağız yemeyince yüz utanmaz.", 
"Ağlama ölü için, ağla deli için.", 
"Ağlamayan çocuğa meme vermezler.", 
"Ağlarsa anam ağlar, gerisi yalan ağlar.", 
"Ağlayak da gözden mi olak?", 
"Ağlayanın malından gülene hayır gelmez.", 
"Ağrısız baş mezarda olur.", 
"Ağustos ayında beyni kaynayanın, zemheride Zahmarıda kazanı kaynar.", 
"Ağustosta beynin kaynasın, kışın da tencere kaynasın.", 
"Ağzı açık ayran delisi.", 
"Ağzına bir zeytin verir, ardına tulum tutar.", 
"Ağzından bal akıyor.", 
"Ah alan unmaz, ah yerde kalmaz.", 
"Ahmak misafir, ev sahibini ağırlar.", 
"Ak akçe kara gün içindir.", 
"Ak gün ağartır‚ kara gün karartır.", 
"Ak ile kara dere kenarında belli olur.", 
"Ak koyunun kara kuzusu da olur.", 
"Ak köpeğe koyun diye sarılma.", 
"Akan su yosun tutmaz.", 
"Akan su, pis tutmaz.", 
"Akçe bulsam, çıkı yok.", 
"Akıl, akıldan üstündür.", 
"Akıl para ile satılmaz.", 
"Akıl yaşta değil baştadır.", 
"Akıl yiğide sermayedir.", 
"Akılı olmayana neylesin sakal, kayışı tarladan götürür çakal.", 
"Akıllı düşünene kadar, deli oğlunu evermiş, torunu olmuş.", 
"Akıllı olan katar katar yer, akılsız olan satar satar yer.", 
"Akılsız başın cezasını ayaklar çeker.", 
"Akılsız köpeği yol kocatır.", 
"Akılsızın şaşkını beyaz giyer kış günü.", 
"Akıntıya kürek çekme, kurak yere ekin ekme.", 
"Akranıyla konuşmayanın sesi, semadan gelir.", 
"Akşam gelen misafirin, yiyeceği bulgur sıkısı, yatacağı ahır sekisi.", 
"Akşamın hayrından sabahın şerri iyidir.", 
"Al elmaya taş atan çok olur.", 
"Al malın iyisini çekme kaygısını.", 
"Al yakışırken, el bakışırken.", 
"Alacağın bir iğne, çeliğin okkasını orantıya vurursun.", 
"Alçak tavuk kendini ferik gösterir.", 
"Alışmış kudurmuştan beterdir.", 
"Alim unutmuş, kalem unutmamış.", 
"Allah aptala eşeğini kaybettirir, sonra buldurup sevindirirmiş.", 
"Allah dağına göre kar verir.", 
"Allah şaşırttı mı, dayıya hala dedirtirmiş.", 
"Allı yelek, pullu yelek, canfes neye gerek?", 
"Alma el kızının ahını, gökten indirir şahini.", 
"Alma mazlumun ahını, çıkar aheste aheste.", 
"Alma mazlumun ahını, gökden indirir şahını.", 
"Almadan vermek Allaha mahsustur.", 
"Almak kolay ödemek zordur.", 
"Altın anahtar, her kapıyı açar.", 
"Altın eşik, ağaç eşiğe muhtaçtır.", 
"Altın kılıç demir kapıyı açar.", 
"Altın yere düşmekle pul olmaz.", 
"Altının değerini sarraf bilir.", 
"Ana gibi yâr, Bağdat gibi diyar olmaz.", 
"Anan gibi saç büyüteceğine, baban gibi bıyık büyüt.", 
"Anan turp, baban şalgam, sen içinde gülbe şeker.", 
"Ananın bastığı yavru incinmez.", 
"Ananın bastığı yerde yavru ölmez.", 
"Anasına bak kızını al, astarına bak bezini al.", 
"Anasına bak kızını al, kenarına bak bezini al.", 
"Anlayana sivrisinek saz, anlamayana davul zurna az.", 
"Aptalın karnı doyunca gözü yolda olur.", 
"Ar gözden, kâr yüzden anlaşılır.", 
"Ar namus hak getire.", 
"Arap eli öpmek, dudak karartmaz.", 
"Arayan belasını da devasını da bulur.", 
"Arayan bulur, inleyen ölür.", 
"Arefe günü yalan söyleyenin, bayram günü yüzü kara çıkar.", 
"Arı bal yapacak çiçeği bilir.", 
"Arı kahrını çekmeyen balın kadrini ne bilir.", 
"Arı satmış namusu tellala vermiş.", 
"Arkadaş dediğinin gölgesinde suç işlenir.", 
"Arkadaşını söyle ki, sana kim olduğunu söyleyeyim.", 
"Arkalı it kurdu boğar.", 
"Armudu sapıyla, üzümü çöpüyle, pekmezi küpüyle.", 
"Arpa eken darı biçmez.", 
"Arpa ekip buğday bekleme.", 
"Asıl azmaz, bal kokmaz; kokarsa yağ kokar, onun da aslı ayrandır.", 
"Aslan yattığı yerden belli olur.", 
"Aslı neyse nesli odur.", 
"Aslına çekmeyen haramzadedir.", 
"Aslında olan tırnağına getirir.", 
"Aslını inkâr eden haramzâdedir.", 
"Aslını inkâr edenin nesli gevşek olur.", 
"Aş kaşık ile, iş keşik ile.", 
"Aş sabahın iş sabahın.", 
"Aşağı tükürsen sakal, yukarı tükürsen bıyık.", 
"Aşk olmayınca meşk olmaz.", 
"At alırsan yazın, deve alırsan güzün, avrat alırsan gezin ha gezin.", 
"At binenin kılıç kuşananındır.", 
"At ile avrat yiğidin ikbalindendir.", 
"At karnından yiğit burnundan bellidir.", 
"At olacak tay yürüyüşünden belli olur.", 
"At ölür itlere bayram olur.", 
"At ölür meydan kalır, yiğit ölür şan kalır.", 
"At ver hasım ol, kız ver hısım ol.", 
"At yedi günde, it yediği günde unutur.", 
"At, sahibine göre kişner.", 
"Ata binmek bir ayıp, inmek iki ayıp.", 
"Ata et, ite ot verilmez.", 
"Ata sözü tutmayan, uluya uluya kalır.", 
"Ateş düştüğü yeri yakar.", 
"Ateş ile barut bir arada olmaz.", 
"Ateş olmayan yerden duman çıkmaz.", 
"Atı alan Üsküdarı geçti.", 
"Atılan ok geri dönmez.", 
"Atımın anlı sakar, lakabını ele takar.", 
"Atın iyisi arkadan gelmez.", 
"Atın iyisine doru, yiğidin iyisine deli derler.", 
"Atın ölümü arpadan olsun.", 
"Atlar tepişirken arada eşekler ezilir.", 
"Atlı, itli sığmış, bir çocuk sığmamış.",
"Attan düşen kaba döşek, eşekten düşen kazma kürek.", 
"Attan düşen ölmez, eşekten düşen ölür.", 
"Attan indi eşeğe bindi.", 
"Avradı er zapt etmez, ar zapt eder.", 
"Avrat var ev yapar, avrat var ev yıkar.", 
"Ay bozmaz, süt kokmaz.", 
"Ayağa değmedik taş, başa gelmedik iş olmaz.", 
"Ayağın sığmayacağı yere baş sokulmaz.", 
"Ayağını yorganına göre uzat.", 
"Aydan gelen halı üstüne, günde gelen kül üstüne.", 
"Ayranım ekşidir diyen olmaz.", 
"Az kazanan çok kazanır, çok kazanan hiç kazanır.", 
"Az menfaat çok zarara mal olur.", 
"Az sabırda, çok keramet vardır.", 
"Az tamah, çok ziyan getirir.", 
"Az veren candan, çok veren maldan verir.", 
"Az yaşa, uz yaşa, akıbet gelecek başa.", 
"Azan mevlasını da bulur, belasını da.", 
"Azı bilmeyen çoğu hiç bilmez.", 
"Azıcık aşım, kaygısız başım.", 
"Azıksız yola çıkanın, iki gözü el torbasında olur.", 
"Azmış, kudurmuştan beterdir.",
"Baba borç yapar çol çocuk aç yatar.", 
"Baba ekmeği zindan ekmeği, koca ekmeği meydan ekmeği.", 
"Baba koruk yer, oğlunun dişi kamaşır.", 
"Baba mirası yanan mum gibidir.", 
"Baba oğula bağ bağışlamış, oğul babaya bir salkım üzüm vermemiş.", 
"Babadan mal kalır, kemal kalmaz.", 
"Baban bana öğüt verirken, ben inek gözünde kırk sinek saydım.", 
"Babası ölen bey, anası ölen kadın olur.", 
"Babasına hayır etmeyenin kimseye hayrı olmaz.", 
"Babaya dayanma, karıya güvenme.", 
"Baca eğride olsa, dumanı doğru çıkar.", 
"Bacak kadar boyu var, türlü türlü huyu var.", 
"Bağ dua değil, çapa dua ister.", 
"Bağa bak üzüm olsun, yemeye yüzün olsun.", 
"Bağa gir izin olsun ki, yemeye yüzün ola.", 
"Bağlı aslana tavşan bile hücum eder.", 
"Bahar çiçeğiyle güzeldir.", 
"Baht olmayınca başa, ne kuruda biter, nede yaşta.", 
"Bakacağın yüze sıçma, sıçacağın yüze bakma.", 
"Bakarsan bağ, bakmazsan dağ olur.", 
"Bakkal ölenin borcunu, diriye ödettirir.", 
"Bakmakla öğrenilseydi, kediler kasap olurdu.", 
"Bal döksen yalanır.", 
"Bal olan yerde sinek de bulunur.", 
"Bal tutan parmağını yalar.", 
"Bal yiyen baldan bıkar.", 
"Bal, bal demekle ağız tatlanmaz.", 
"Balı parmağı uzun olan değil, kısmeti olan yer.", 
"Bana benden olur, her ne olursa, başım rahat bulur, dilim durursa.", 
"Bana dokunmayan yılan bin yıl yaşasın.", 
"Baskın basanındır.", 
"Baskısız yongayı yel alır.", 
"Bastığın yer bayram olsun.", 
"Baş başa, baş da padişaha bağlıdır.", 
"Baş nereye giderse, oyak oradadır.", 
"Başıma uymayan takke elin olsun.", 
"Başındaki fese bak, girdiği kümese bak.", 
"Başını ecemi berbere teslim eden, cebinde pamuk eksik etmesin.", 
"Başsız evin köpeği çok havlar.", 
"Bazen inek, erkek; bazen de dişi doğurur.", 
"Bebeler birbirinden huy kapar, ayranlarına su katar.", 
"Bedava sirke baldan tatlıdır.", 
"Bekâr gözü ile kız alınmaz.", 
"Bekâr gözü kör gözü.", 
"Bekâra karı boşamak kolay gelir.", 
"Bekârlık maskaralıktır.", 
"Bekarın ahmağı akşam, evlinin ahmağı sabah traş olur.", 
"Bekârın parasını it yer, yakasını bit.", 
"Bekleyen derviş muradına ermiş.", 
"Beleş peynir fare kapanında bulunur.", 
"Belli düşman, gizli dosttan yeğdir.", 
"Benden sana öğüt, ununu elinle öğüt.", 
"Benim adım Hıdır, elimden gelen budur.", 
"Benim sakalım tutuştu, sen cigara yakmak istersin.", 
"Besle kargayı oysun gözünü.", 
"Besledik büyüttük danayı, şimdi tanımaz oldu anayı, babayı.", 
"Beş kuruşluk fener o kadar yanar.", 
"Beş parmağın beşi de bir değil.", 
"Beyaz saç, aklın değil yaşın işaretidir.", 
"Bıçak sapını kesmez.", 
"Bıçak yarası geçer, dil yarası geçmez.", 
"Bıldır ki hurmalar götünü tırmalar.", 
"Bilgisiz insan meyvesiz ağaca benzer.", 
"Bilinmedik aş, ya karın ağrıtır ya baş.", 
"Bilmediği beş vakit namaz, bilirde yanına varmaz.", 
"Bilmediklerimi ayağımın altına koysam, başım göğe değer.", 
"Bilmemek ayıp değil öğrenmemek ayıptır.", 
"Bin atın varsa bin dinlen, bir atın varsa in dinlen.", 
"Bin bilsen de bir bilene danış.", 
"Bin dinle, bir söyle.", 
"Bin ölçüp bir biçmeli.", 
"Binde bir gelinen yere gül döşerler, her gün gelinen yere kül döşerler.", 
"Bir adamın adı çıkacağına, canı çıksın.", 
"Bir adamın karısı onun yarısıdır.", 
"Bir ağaçta gül de biter, diken de.", 
"Bir ağaçtan, oklukta çıkar boklukta.", 
"Bir ağızdan çıkan, bin ağza yayılır.", 
"Bir ahırda at da bulunur eşek de.", 
"Bir ayağı çukurda.", 
"Bir bulutla kış gelmez.", 
"Bir bütün bir yarımdan iyidir.", 
"Bir dalın gölgesinde bin koyun eğlenir.", 
"Bir dirhem et, bin ayıp örter.", 
"Bir elin nesi var, iki elin sesi var.", 
"Bir elin verdiğini, öbür elin duymasın.", 
"Bir eve bir baca, bir kadına bir koca.",
"Bir fincan kahvenin kırk yıl hatırı vardır.", 
"Bir işe başlamak, bitirmenin yarısıdır.", 
"Bir koyun başı pişinceye kadar, kırk kuzu başı pişer.", 
"Bir koyundan iki post olmaz.", 
"Bir musibet bin nasihatten iyidir.", 
"Bir nalına vurur, bir mıhına.", 
"Bir yerim diyenden birde yemem diyenden kork.", 
"Bir yiğit kırk yılda meydana gelir.", 
"Biri eşikte, biri beşikte.", 
"Biri yer, biri bakar, kıyamet ondan kopar.", 
"Birlikten kuvet doğar.", 
"Bitli baklanın kör alıcısı olur.", 
"Bize gelince yiyip içelim, size gelince gülüp geçelim.", 
"Boğulursan büyük suda -denizde- boğul.", 
"Borcun iyisi vermek, derdin iyisi ölmektir.", 
"Borç yiğidin kamçısıdır.", 
"Boş duranı Allah da sevmez kuluda.", 
"Boş fıçı çok langırdar.", 
"Boşboğazı cehenneme atmışlar, ‘odun yaş’ diye bağırmış.", 
"Boşboğazın sigarası yanmaz.", 
"Bu dünya iki kapılı handır, gelen bilmez giden bilmez.", 
"Bugünün küçükleri yarının büyükleri.", 
"Budalanın yağı çok olursa sakalına sürer.", 
"Bugün bana ise yarın sana.", 
"Bugünkü işini yarına bırakma.", 
"Bugünkü tavuk, yârınki kazdan iyidir.", 
"Bülbülü altın kafese koymuşlar ah vatanım demiş.", 
"Bülbülün çektiği; dili belasıdır.", 
"Büyük ekmek, büyük bezeden olur.", 
"Büyük lokma çukurda kalır.", 
"Büyük lokma ye, büyük söz söyleme.", 
"Büyük zekâlar birlikte düşünürler.",
"Cahil adam meyve vermeyen ağaca benzer.", 
"Cahile söz anlatmaktansa, deveye hendek atlatmak iyidir.", 
"Cahilin dostluğundan alimin düşmanlığı yeğdir.", 
"Cahille arkadaş olma küstürün, cam kırığıyla kıçını silme kestirirsin.", 
"Cami ne kadar büyük olsa imam bildiğini okur.", 
"Caminin kapısını bilmez, sofuluk taslar.", 
"Can boğazdan gelir.", 
"Can cümleden azizdir.", 
"Can çıkar, huy çıkmaz.", 
"Can çıkmadan ümit kesilmez.", 
"Cana gelecek mala gelsin.", 
"Canı kaymak isteyen mandayı yanında taşır.", 
"Canı yanan eşek atı geçer.", 
"Cefayı çekmeyen sefanın kadrini bilemez.", 
"Cins kedi ölüsünü göstermez.", 
"Cömert derler, maldan ederler, yiğit derler candan ederler.", 
"Cömert ile nekesin harcı birdir.",
"Çabuk parlayan çabuk söner.", 
"Çağrılan yere erinme, çağrılmayan yere görünme.", 
"Çağrıldığın yere git, ar eyleme; çağrılmadığın yere gidip yerini dar eyleme.", 
"Çağrılmadık yere, çörekçi ile börekçi gider.", 
"Çalıda gül bitmez, cahile söz yetmez.", 
"Çalışan demir pas tutmaz; çünkü ölür.", 
"Çalışmak ibadetin yarısıdır.", 
"Çalma elin kapısını, çalarlar kapını.", 
"Çamura taş atma üstüne sıçrar.", 
"Çatal kazık yere batmaz.", 
"Çıngıraklı deve kaybolmaz.", 
"Çıracı olsam ay akşamdan doğar.", 
"Çiftçilik, eşeğin kuyruğuna benzer, ne uzar ne kısalır.", 
"Çiftçinin karnını yarmışlar, kırk tane gelecek yıl çıkmış.", 
"Çiftçiye yağmur, yolcuya kurak, cümlenin muradını verecek hak.", 
"Çingene ciğer pişirir, yemeden karnını şişirir.", 
"Çingenenin ipini, kendisine çektirirler.", 
"Çingeneye beylik vermişler, önce babasını asmış.", 
"Çirkefe taş atma, üzerine sıçrar.", 
"Çoban ne yesinki köpeğine yedirsin.", 
"Çocuğa iş buyuran, ardınca kendi gider.", 
"Çocuk oyundan, aptal düğünden usanmaz.", 
"Çocuğu işe gönder, peşinden sen git.", 
"Çocuk evin meyvesidir.", 
"Çocuktan al haberi.", 
"Çok söyleme arsız edersin, aç bırakma hırsız edersin.", 
"Çok söz yalansız, çok para haramsız olmaz.", 
"Çok yaşayan bilmez çok gezen bilir.", 
"Çubuk iken çıtlamayan, hezen iken kütlemez.", 
"Çürük iple kuyuya inilmez.", 
"Çürük tahtaya çivi çakılmaz.",
"Dağ başından duman eksik olmaz.", 
"Dağ dağ üstünde olur, ev ev üstünde olmaz.", 
"Dağ dağa kavuşmaz insan insana kavuşur.", 
"Dağ dumansız insan hatasız olmaz.", 
"Damlaya damlaya göl olur.", 
"Danışan dağ aşmış,danışmayan yolu şaşmış.", 
"Darı unundan baklava,incir ağacından oklava olmaz.", 
"Darlıkta dirlik olmaz.", 
"Davetsiz gelen döşeksiz oturur.", 
"Davul dengi dengine çalar.", 
"Davulun sesi uzaktan hoş gelir.", 
"Deme dostuna, der dostuna.", 
"Demir nemden insan gamdan çürür.", 
"Demir tavında dövülür.", 
"Demir tavında, dilber çağında.", 
"Deniz sevilir de, densiz sevilmez.", 
"Deniz yoğurt olmuş da yemeye kaşık bulunmamış.", 
"Denize düşen yağmurdan korkmazmış.", 
"Denize düşen yılana sarılır.", 
"Derdini söylemeyen derman bulamaz.", 
"Dereyi görmeden paçayı sıvama.", 
"Dert saklayanda kalır.", 
"Dervişin fikri ne ise zikri de odur.", 
"Devden büyük dert var.", 
"Deve boynuz ararken kulaktan olmuş.", 
"Deveyi yardan atlatan, bir tutam ottur.", 
"Dibi görünmeyen sudan geçme.", 
"Dikensiz gül olmaz.", 
"Dinsizin hakkından imansız gelir.", 
"Dinsizin ipi ile Kuyuya inilmez.", 
"Dişi kuş yapar yuvayı, içini dışını sıvayı sıvayı.", 
"Doğru söyleyeni Dokuz köyde kovarlar.", 
"Doğru söyleyenin bir ayağı üzengide gerek.", 
"Domuzdan post gavurdan dost olmaz.", 
"Dost acı söyler.", 
"Dost başa düşman ayağa bakar.", 
"Dost kara günde belli olur.", 
"Dost kazandost; düşman anadan da doğar.", 
"Dost yüzünden, düşman gözünden belli olur.", 
"Döğüşerek pazarlık et, güle güle ayrıl.", 
"Dut kurusuyla yar sevilmez.", 
"Dünya malı dünyada kalır.", 
"Dünya Sultan Süleyman'a bile kalmamış.", 
"Düşenin dostu olmaz.", 
"Düşman ayağa dost basa bakar.", 
"Düşmanı karıncaysa, sen fil olur.", 
"Düşmanın karıncaysa da kork.", 
"Düt demeye dudak gerek.",
"Ecel geldi cihane, baş ağrısı bahane.", 
"Ecele çare olmaz.", 
"Eceli gelen keçi, çobanın ekmeğini yer.", 
"Eceli gelen köpek cami duvarına siyer.", 
"Eğilen baş kesilmez.", 
"Eğreti ata binen tez iner.", 
"Eğri oturalım doğru konusalım.", 
"Ek tohumun hasını, çekme yiyecek yasını.", 
"Eken biçer, konan göçer.", 
"Ekmeğin büyüğü hamurun çoğundan olur.", 
"Ekmeğin kestiğini kılıç kesmez.", 
"El ağzı ile çorba içilmez.", 
"El atına binen yaya kalır.", 
"El deliye, bende akıllıya muhtacım.", 
"El elden üstündür.", 
"El elin eşeğini türkü çağırarak arar.", 
"El içinde vasiyet ettik, ölmemek olmaz.", 
"El kazanı ile aş kaynamaz.", 
"El yarası onar, dil yarası onmaz.", 
"El yumruğu yemeyen, kendi yumruğunu balyoz sanır.", 
"Elden gelen öğün olmaz, o da vaktinde bulunmaz.", 
"Eli dar olanın, dili kısa olur.", 
"Eli doluya: ağa buyur, eli boşa: ağa uyur.", 
"Eli ile köfte yuvarlıyor, gözü kırık kovalıyor.", 
"Elin hamuru ile erkek işine karışma.", 
"Elin ile koymadığını kaldırma.", 
"Elmanın dibi göl, armudun dibi yol (olmalı).", 
"Elmayı soy da ye, armudu say da ye.", 
"Emanet (Amanat) ata binen, tez iner.", 
"Emanet eşeğin yuları gevşek olur.", 
"Erkek arslan arslan da, dişi arslan arslan değil mi?",
"Erkek koyun kasap dükkânına yakışır.", 
"Erken evlenen döl alır, erken kalkan yol alır.", 
"Erken evlenen yanılmamış.", 
"Esirgenen göze çöp batar.", 
"Eşek hoşaftan ne anlar; suyunu içer, denesi kalır.", 
"Eşek olduktan sonra semer vuran çok olur.", 
"Eşekler çalışır, atlar yer.", 
"Eşekten at olmaz, ciğerinden aş olmaz.", 
"Et tırnaktan ayrılmaz.", 
"Ev sahibinin hatırı olmazsa köpeğini dövmek kolaydır.", 
"Evdeki hesap çarşıya uymaz.", 
"Evin danası evin öküzünden korkmaz.", 
"Evlenenle ev alana (yapana) Allah yardım eder.", 
"Evladı ben doğurdum ama gönlü benim değil ki.", 
"Evlinin (ev sahibinin) bir evi var, evsizin (kiracının) bin evi var.", 
"Eyyam sana uymazsa sen eyyama uy.",
"Fakir oynayacağı zaman davul patlar.", 
"Fakir parasız olan değil akılsız olandır.", 
"Fakirin ekmegi umuttur.", 
"Fakirin tavuğu tek tek yumurtlar.", 
"Fakirlik ayıp değil, tembellik ayıp.", 
"Faydasız baş, mezara yaraşır.", 
"Fazla naz aşık usandırır.", 
"Fırsat eldeyken sürün devranı.", 
"Fukaranın düşkünü, beyaz giyer kış günü.",
"Gafile kelam, nafile kelam.", 
"Garip kuşun yuvasını Allah yapar.", 
"Gavurun tembeli keşiş, Müslümanın tembeli derviş.", 
"Geçtiğin köprüleri yakma.", 
"Gel demek kolay, git demek güçtür.", 
"Gelen gideni aratır.", 
"Gelin ata binmişde, görkü kimin kapıya inmiş.", 
"Gelin bindi deveye gör kısmeti nereye.", 
"Gem almayan atın ölümü yakındır.", 
"Gençlikte taş taşı, kocalıkta ye aşı.", 
"Geniş günün de dar gezen, dar günün de geniş gezer.", 
"Gerçek dost kötü günde belli olur.", 
"Gergin ip, çabuk kopar.", 
"Gezen ayağa taş değer.", 
"Gitti ağalar paşalar, kellere kaldı köşeler.", 
"Gittiğin yer kör ise, gözünü yum da bak.", 
"Gizliden gebe kalan, aşikâre doğurur.", 
"Göğe direk, denize kapak olmaz.", 
"Görünen dağın uzağı olmaz.", 
"Görünen köy kılavuz istemez.", 
"Göz görmeyince gönül katlanır.", 
"Göz görür, gönül çeker.", 
"Göz odur ki dağın arkasını göre,akıl odur ki başa geleceği bile.", 
"Gözün ile görmediğini söyleme.", 
"Gülme komşuna gelir başına.", 
"Gülü seven, dikenine katlanır.", 
"Gündüz yenilen hurmalar, gece mideni tırmalar.", 
"Güneş balçıkla sıvanmaz.", 
"Güneş giren eve hekim girmez.", 
"Güneş girmeyen eve doktor girer.", 
"Güttüğü iki keçi, ıslığı dağı taşı tuttu.", 
"Güzel gözünden, yiğit sözünden belli olur.",
"Hacı Mekke’de, derviş tekkede.", 
"Hacı olmayacak hacıyı deve üstünde yılan sokar.", 
"Hak deyince akan sular durur.", 
"Hak doğrunun yardımcısıdır.", 
"Halaya giren kolunu sallar.", 
"Hamala semeri yük olmaz.", 
"Harman yel ile, düğün el ile olur.", 
"Hasta sağ kalırsa hekime karşı gelir.", 
"Hasta yatan değil, eceli gelen ölür.", 
"Havada ahreni ile uçmayan kuşun sesi havadan değil, tavadan gelir.", 
"Haydan gelen huya gider.", 
"Hazıra hanak, pişmişe konak.", 
"Helal kazanç ile pilav yenmez.", 
"Hem kız, hem baldırı düz hem de ucuz olur mu?", 
"Her akla geleni işleme her ağacı taslama.", 
"Her işin başı sağlık.", 
"Her işte bir hayır vardır.", 
"Her koyun kendi bacağından asılır.", 
"Her kuşun eti yenmez.", 
"Her şakanın altında bir gerçek yatar.", 
"Her şey incelikten insan kabalıktan kırılır.", 
"Her şeyin yenisi, dostun eskisi.", 
"Her taş baş yarmaz.", 
"Her yiğidin bir yoğurt yiyişi vardır.", 
"Her zamanı bir sayma.", 
"Herkes aklını pazara çıkarmış, yine kendi aklını beğenmiş.", 
"Herkes kaşık yapar ama sapını yapamaz.", 
"Herkesin aklı bir olsaydı, koyunlara çoban bulunmazdı.", 
"Hırsız sekiz, köşe dokuz.", 
"Hızlı giden atın boku seyrek düşer.", 
"Hile ile iş gören mihnet ile can verir.", 
"Hocanın dediğini tut, yoluna gitme.", 
"Horoz ölür, gözü çöplükte kalır.", 
"Horozu çok olan köyün sabahı geç olur.", 
"Huylu huyundan vazgeçmez.",
"Ihlamurdan odun olmaz, beslemeden kadın olmaz.", 
"Irmak kenarına çeşme yapılmaz.", 
"Irmaktan geçerken at değiştirilmez.", 
"Isıran it, dişini göstermez.", 
"Isırgan ile taharet olmaz.", 
"Islanmışın yağmurdan pervası yoktur.", 
"Ismarlama hac, hac olmaz.", 
"Işığını akşamdan önce yakan sabaha çırasında yağ bulamaz.", 
"İbadet de gizli, kabahat da.", 
"İğneyi kendine, çuvaldızı ele batır.", 
"İki aslan bir posta sığmaz.", 
"İki baş bir kazanda kaynamaz.", 
"İki cambaz bir ipte oynamaz.", 
"İki çıplak bir hamama yakışır.", 
"İki gönül bir olunca (olursa) samanlık seyran olur.", 
"İnsan kocar, gönlü kocamaz.", 
"İnsan konuşa konuşa, hayvan koklaşa koklaşa (anlaşır).", 
"İnsan sözünden, hayvan yularından tutulur.", 
"İnsan yedisinde ne ise yetmişinde de odur.", 
"İp inceldiği yerden kopar.", 
"İp kırıldığı yerden ulanır(eklenir).", 
"İstediğini söyleyen, istemediğini işitir.", 
"İstemek bir ayıp, vermemek iki ayıp.", 
"İsteyenin bir yüzü kara, vermeyenin iki yüzü.", 
"İşin yoksa şahit ol, paran çoksa kefil ol.", 
"İşini kış tut, yaz tutarsa bahtına.", 
"İşleyen demir ışıldar.", 
"İt ite buyurur, it de kuyruğuna.", 
"İt iti ısırmaz.", 
"İt kağnının gölgesine yatmış, ne koyu gölgem var demiş.", 
"İt utansa don giyer.", 
"İt ürür kervan yürür.", 
"İti an çomağı hazırla.", 
"İti, öldürene sürütürler.", 
"İtin ısırmayanı, atın osurmayanı olmaz.", 
"İven (acele eden) kız ere varmaz, varsa da baht bulmaz.", 
"İyi insan lafının üzerine gelirmiş.", 
"İyiliğe karşı iyilik her kişinin işi, kötülüğe karşı iyilik er kişinin işi.",
"Kaçan balık büyük olur.", 
"Kaçan kızın bohçası küçük (hafif) olur.", 
"Kadı anlatana göre fetva verir.", 
"Kadının biri alâ, ikisi belâdır.", 
"Kâfirden hacı, elden bacı olmaz.", 
"Kakma el kapısını el ucuyla, yiterler kapını var (olanca) gücüyle.", 
"Kalem kılıçtan üstündür.", 
"Kanaat gibi devlet olmaz.",
"Karamanın koyunu, sonra çıkar oyunu.", 
"Karga bülbülü taklit edeyim derken, ötmeyi unutmuş.", 
"Karınca kanatlanınca serçe oldum sanır.", 
"Karnının doymayacağı yere, açlığını bildirme.", 
"Kasap et derdinde koyun can derdinde.", 
"Kasap sevdiği postu yere vurur.", 
"Kaşıkla verip, sapıyla gözünü çıkartma.", 
"Katranı kaynatsan olur mu şeker, cinsi batasıca mutlaka cinsine çeker.", 
"Kavakta nar olmaz, kötülerde ar olmaz.", 
"Kaz gelecek yerden tavuk esirgenmez.", 
"Kazma kuyuyu, kazarlar kuyunu.", 
"Keçinin canı teke isteyince, çobanın değneğine (sopasına) sürtünür.", 
"Kedi gidince fare bey olur.", 
"Kedinin kanatları olsaydı, serçenin soyu tükenirdi.", 
"Kediye kanat takarsan gökte serçe bırakmaz.", 
"Kel yanında kabak anılmaz.", 
"Kenarına bak bezini al, anasına bak kızını al.", 
"Kendi düşen ağlamaz.", 
"Keskin sirke küpüne zarar verir.", 
"Kılıç kınını kesmez.", 
"Kırk hırsız bir çıplağı soyamaz.", 
"Kırk yıl ecel yağsa, eceli gelen ölür.", 
"Kız beşikte çeyiz sandıkta.", 
"Kızım sana diyorum, gelinim sen anla.", 
"Kızın kimi severse güveyin odur, oğlun kimi severse gelinin odur.", 
"Kızını dövmeyen dizini döver.", 
"Kimi bağ bozar, kimi bostan bozar.", 
"Kimi yer, kimi bakar; kıyamet ondan kopar.", 
"Kişi refikinden azar.", 
"Kişiyi nasıl bilirsin, kendin gibi.", 
"Kol kırılır, yen içinde kalır.", 
"Komşu komşunun külüne muhtaçtır.", 
"Komşuda pişer, bizede düşer.", 
"Komşunun tavuğu komşuya kaz görünür.", 
"Kork korkmazdan‚ utan utanmazdan.", 
"Koyunun bulunmadığı yerde keçiye Abdurrahman çelebi derler.", 
"Köpekle dalaşmaktansa, çalıyı dolanmak hayırlıdır.", 
"Köpeklerin duası kabul olsa gökten kemik yağar.", 
"Köpeksiz köy bulmuş, değneksiz dolaşıyor.", 
"Köpeksiz köyde değnekle gezilmez.", 
"Köprüyü gecene kadar, ayıya dayı de.", 
"Kör alıcının kör satıcısı vardır.", 
"Körler sağırlar birbirini ağırlar.", 
"Kötü komşu insanı mal sahibi yapar.", 
"Kötü tarlanın verdiğini, yiğit kardeş vermez.", 
"Kurt kocayınca köpeğin maskarası olur.", 
"Kurt kuzu kaptığı yeri dokuz defa yoklar.", 
"Kuru laf karın doyurmaz.", 
"Kurunun yanında yaş da yanar.", 
"Kusursuz dost arayan dostsuz kalır.",
"Laf ile karın doymaz.", 
"Laf ile peynir gemisi yürümez.", 
"Laf lafı açar.", 
"Laf torbaya girmez.", 
"Lafın azı uzu, çobana verme kızı, ya koyun güttürür ya kuzu.", 
"Lakırdı lakırdıyı açar, lakırdı bilmeyen meclisten kaçar.", 
"Latife latif gerek.", 
"Lâzıma hazine yetmez, elverire para gitmez.", 
"Leyleğin ömrü laklak ile geçer.", 
"Lezzetsiz çorbaya tuz kâr etmez.", 
"Lisan gönlün tercümanıdır.", 
"Lokma bile çiğnemeden yutulmaz.", 
"Lokma karın doyurmaz, şefkat artırır.",
"Mahkeme kadıya mülk değil.", 
"Mal canı kazanmaz, can malı kazanır.", 
"Mart ayı, dert ayı.", 
"Mart kapıdan baktırır kazma kürek yaktırır.", 
"Merhametten maraz doğar.", 
"Minareyi çalan kılıfını hazırlar.", 
"Minnetle gül koklama, dikeni sancar seni.", 
"Misafir umduğunu değil, bulduğunu yer.", 
"Mum dibine ışık vermez.", 
"Müflis bezirgân, eski defterlerini karıştırır.", 
"Mühür kimde ise Süleyman odur.",
"Namazda gözü olmayanın kulağı ezanda olmaz.", 
"Ne doğrarsan aşına, o çıkar kaşığına.", 
"Ne yavuz ol asıl, ne yavaş ol basıl.", 
"Nefesine güvenen borazancı başı olur.", 
"Nerede birlik, orada dirlik.", 
"Nerede hareket, orada bereket.", 
"Nush ile uslanmayanı etmeli tekdir; tekdir ile uslanmayanın hakkı kötektir.",
"Oduncunun gözü omcada (bağ kütüğü) dilencinin gözü çömcede (tahta kepçe).", 
"Oğlan dayıya, kız halaya çeker.", 
"Oğlanınki oğul bağı, kızınki bahçe gülü.", 
"Okumayı sevmeyene dokuz hoca az.", 
"Olacakla öleceğe çare yoktur.", 
"Olmaz olmaz deme, olmaz olmaz.", 
"Onbeşindeki kız ya erdedir, ya yerde.", 
"Ortak atın beli kırık olur.", 
"Osmanlı’nın ekmeği dizindedir.", 
"Osurmadan bu memlekette sıçtı derler.", 
"Otu çek köküne bak.", 
"Oynayamayan gelin yerim dar dermiş.", 
"Oğlan yer oyuna gider, çoban yer koyuna gider.",
"Ödünç güle güle gelir, ağlaya ağlaya gider.", 
"Öfke gelir gider, kelle gider gelmez.", 
"Öfkeyle kalkan zararla oturur.", 
"Öğüt, bir hazine kadar değerli olduğu halde genellikle bedava verilir.", 
"Ölecek tavşan çomağa karşı gelir.", 
"Ölmüş eşek kurttan korkmaz.", 
"Ölümü gören, hastalığa razı olur.", 
"Ölürse yer beğensin‚ kalırsa el beğensin.", 
"Ölüsü olan bir gün, delisi olan her gün ağlar.", 
"Öz ağlamayınca göz ağlamaz (yaşarmaz).",
"Padişah yasağı üç gün sürer.", 
"Palamut çok biterse kış erken olur.", 
"Papaz her gün pilav yemez.", 
"Para ile imanın kimde olduğu bilinmez.", 
"Para insana dil, elbise insana yol öğretir.", 
"Parasız pazara, kefensiz mezara gidilmez.", 
"Paraya nereye gidiyorsun demişler, çoğun olduğu yere demiş.", 
"Pek yaş olma, sıkılırsın; pek de kuru olma, kırılırsın.", 
"Perşembenin gelişi, çarşambadan bellidir.", 
"Pilav yiyen, kaşığı belinde gerek.", 
"Pilavdan dönenin kaşığı kırılsın.", 
"Pire itte (köpekte), bit yiğitte bulunur.", 
"Pisboğaz ile boş boğaz, beladan kurtulmaz.",
"Rağbet güzel ile zenginedir.", 
"Rahat ararsan mezarda.", 
"Ramazanda yalan söyleyenin yüzü, bayramda kara olur.", 
"Rençper kırk yılda, tüccar kırk günde.", 
"Rüşvet kapıdan girince insaf bacadan çıkar.", 
"Rüzgâr eken fırtına biçer.", 
"Rüzgâr esmeyince yaprak oynamaz.", 
"Rüzgâra tüküren kendi yüzüne tükürür.", 
"Rüzgârlı havanın kuytusu, yağmurlu havanın uykusu.",
"Sabır acıdır, meyvesi tatlıdır.", 
"Sabreden derviş muradına ermiş.", 
"Saç sefadan, tırnak cefadan uzar.", 
"Sakalda keramet olsa, keçi şeyhlik ederdi.", 
"Sakınan göze çöp batar.", 
"Sakla samanı gelir zamanı.", 
"Saman elinse samanlıkta mı elin?",
"Sanat altın bileziktir.", 
"Sayılı koyunu kurt kapmaz.", 
"Sen işlersen mal işler, insan böyle genişler.", 
"Sen kendini övme el seni övsün.", 
"Sen seversen oğlunu, o da sever oğlunu.", 
"Sev beni, seveyim seni.", 
"Soğuk su, sıcak aş diş düşmanı, genç avrat koca herifin baş düşmanı.", 
"Sopayı yiyen eşek, atı geçer.", 
"Soydur çeker, huydur geçer.", 
"Sormaz ki bilsin, sorsa bilirdi; bilmez ki sorsun, bilse sorardı.", 
"Söyle arkadaşını söyleyeyim sana seni.", 
"Söyleme dostuna, o da söyler dostuna.", 
"Söylemeyen ağız, söyleyen ağzı yorar.", 
"Söz büyüğün sus küçüğün.", 
"Söz gümüş sükût altın.", 
"Söz var insanı yola getirir, söz var insanı yoldan çıkartır.", 
"Söz var iş bitirir, söz var baş yitirir.", 
"Su akar yatağını bulur.", 
"Su akarken küpünü doldurur.", 
"Su akmayınca durulmaz.", 
"Su bulanmayınca durulmaz.", 
"Su testisi su yolunda kırılır.", 
"Suç gelin olsa güvey bulunmaz.", 
"Sütten ağzı yanan, yoğurdu üfleyerek yer.",
"Şahin ile deve avlanmaz.", 
"Şahin küçük et yer, deve büyük ot yer.", 
"Şapkası dar gelen, başım büyük sanır.", 
"Şaraptan bozma sirke keskin olur.", 
"Şaşkın ördek kıçın kıçın dalarmış.", 
"Şaşkın ördek, tersten dalar.", 
"Şaşkın ördek başını bırakır, kıçından dalar.", 
"Şer işi uzat hayra dönsün, hayır işi uzatma şerre dönmesin.", 
"Şeriatın kestiği parmak acımaz.", 
"Şeytanla ortak buğday eken samanını alır.", 
"Şeytanla saman eken, sapını alır.", 
"Şimşek çakmadan gök gürlemez.",
"Tabancanın dolusu bir kişiyi, boşu kırk kişiyi korkutur.", 
"Tandır başında bağ dikmek kolaydır.", 
"Tartılırsan denginle tartıl.", 
"Tasa doyurur, acı acıktırır.", 
"Taş yerinde ağırdır.", 
"Taşıma su ile değirmen dönmez.", 
"Tatlı söz (dil) yılanı deliğinden çıkarır.", 
"Tavşan (Fare) dağa küsmüş dağın haberi olmamış.", 
"Tekkeyi bekleyen, çorbayı içer.", 
"Tembele iş buyur sana akıl öğretsin.", 
"Tereciye tere satılmaz.", 
"Tırnağın varsa başını kaşı.", 
"Tırnağın varsa kaşın, yoksa düşün.", 
"Tilkinin dönüp dolaşıp geleceği yer kürkçü dükkânıdır.", 
"Tok açın halinden anlamaz.", 
"Tok ağırlaması güçtür.", 
"Topalla gezen aksama öğrenir.", 
"Türk’ün Türk’ten başka dostu yoktur.",
"Ucuna bak bezini al, anasına bak kızını al.", 
"Ucuzdur vardır bir illeti, pahalıdır vardır bir hikmeti.", 
"Ulu sözü dinlemeyen uluya kalır.", 
"Ulular köprü olsa basıp geçme.", 
"Ummadığın taş baş yarar.", 
"Umut fakirin ekmeğidir.", 
"Ustanın çekici bin altın.", 
"Uşağı işe koş, sende ardına düş.", 
"Uyku ölümün kardeşidir.", 
"Uyuyan yılanın kuyruğuna basılmaz.", 
"Uzaktan davulun sesi hoş gelir.",
"Üç elli, yaz belli.", 
"Üç göç, bir yangının yerini tutar.", 
"Ürkütme kurbağayı, yiğit edersin.", 
"Ürümesini bilmeyen it, sürüye getirir kurt.", 
"Üşenenin oğlu, kızı olmamış.", 
"Üveye etme özünde bulursun, geline etme kızında bulursun.", 
"Üzerine laf düşmedikçe uyu.", 
"Üzüm üzüme baka baka kararır.", 
"Üzümün çöpü var, armudun sapı.", 
"Üzümünü ye, bağını sorma.",
"Vakit nakittir.", 
"Vakitsiz açılan (açan) gül çabuk solar.", 
"Vakitsiz öten horozun başını keserler.", 
"Var evi, kerem evi; yok evi, verem evi.", 
"Var ne bilsin yokun halinden.", 
"Varda topu gibi yatsıda patlar.", 
"Vardan, yoktan anlamaz.", 
"Varsa eşin rahattır başın, yoksa eşin zordur işin.", 
"Varsa hünerin, her yerde vardır yerin.", 
"Varsa pulun, herkes kulun; yoksa pulun dardır yolun.", 
"Venedik'ten tiryâk (panzehir) gelinceye kadar, Mısırda adamı yılan helâk eder.", 
"Veren el, alandan üstündür.", 
"Veresiye şarap içen iki kere sarhoş olur.", 
"Verirsen doyur‚ vurursan duyur.", 
"Vurursan acıt, yedirirsen doyur.", 
"Vücut kocar, gönül kocamaz.",
"Yabancı koyun kenarda yatar.", 
"Yağ yiyen köpek tüyünden belli olur.", 
"Yağmurlu gün tavuk su içmez.", 
"Yalancı kim? İşittiğini söyleyen.", 
"Yalancının mumu yatsıya kadar yanar.", 
"Yalın varsa karnına, çulun varsa sırtına.", 
"Yanık yerin otu tez biter.", 
"Yanlış hesap Bağdat'tan döner.", 
"Yardımcının yardımcısı olur.", 
"Yarım hekim candan, yarım hoca dinden eder.", 
"Yaş kesen baş keser.", 
"Yazın başı pişenin, kışın aşı pişer.", 
"Yazın eli yaş olanın, kışın ağzı yaş olur.", 
"Yazın gölge hoş kışın çuval boş.", 
"Yemeye hazır dayanmaz.", 
"Yenice elek duvarda gerek.", 
"Yenilen pehlivan, güreşe doymaz.", 
"Yiğidi öldür; hakkını yeme.", 
"Yol sormakla bulunur.", 
"Yol üstüne bostan ekme el için, kocalıkta (ihtiyarlıkta) avrat alma el için.", 
"Yol yürümeyle, borç ödemeyle biter.", 
"Yola giden yorulmaz.", 
"Yolu yordamıyla, ormanı baltayla (geçersin-bitirirsin).", 
"Yolundan giden yorulmaz.", 
"Yöğrük at yemini artırır.", 
"Yuvarlanan taş, yosun tutmaz.", 
"Yük altında ancak eşek (HAMAL)kalır.",
"Zahmetsiz rahmet olmaz.", 
"Zaman sana uymazsa sen zamana uy.", 
"Zan, hatıranın yalanıdır.", 
"Zannetmediğin yerden tilki çıkar.", 
"Zalim kadıdan insaflı subaşı yeğdir.", 
"Zarar faydanın kardeşidir.", 
"Zararın neresinden dönersen (dönülürse) kârdır.", 
"Zâtı memduh olanın sıfata ihtiyacı yoktur.", 
"Zelzeleyi gören yangına razı olur.", 
"Zemheride sür de çalı ile sür.", 
"Zemheride yoğurt isteyen, cebinde bir inek taşır.", 
"Zemheriden sonra ekilen darıdan, kocasından sonra kalkan karıdan hayır gelmez.", 
"Zengin adam, elindeki kendine yeten adamdır.", 
"Zengin arabasını dağdan aşırır, züğürt düz ovada yolunu şaşırır.", 
"Zengin dağlar aşar, olmayan yolda şaşar.", 
"Zengin kesesini, züğürt dizini döver.", 
"Zengin helvasını baldan pişirir, züğürt derman için pekmez bulamaz.", 
"Zengine bir kıvılcım, güzele bir sivilce yetermiş.", 
"Zengine dokun geç, züğürtten sakın geç.", 
"Zenginin basması ipekli görünür.", 
"Zenginin gönlü olasıya, fakirin canı çıkar."]

function getQuote() {
    var randomNumber = Math.floor(Math.random() * quotes.length)
    document.getElementById("newQuoteSection").innerText = quotes[randomNumber]
}